#!/usr/bin/python

DOMAIN = "mintinstall"
PATH = "/usr/share/linuxmint/locale"

import os, gettext, sys
sys.path.append('/usr/lib/linuxmint/common')
import additionalfiles

os.environ['LANG'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=gksu mintinstall
Icon=mintinstall
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
NotShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintinstall.desktop", prefix, _("Software Manager"), _("Install new applications"), suffix)

suffix = """Exec=kdesudo -i /usr/share/icons/hicolors/48x48/apps/software-properties-mint.png -d --comment "<b>Please enter your password to start the software manager</b>" mintinstall
Icon=software-properties-mint
Terminal=false
Type=Application
Encoding=UTF-8
Categories=System;
OnlyShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintinstall-kde.desktop", prefix, _("Software Manager"), _("Install new applications"), suffix, genericName=_("Install new applications"))

suffix = """Exec=mintInstall
Icon=/usr/share/linuxmint/logo.png
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
NoDisplay=true
MimeType=application/x-mint;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintinstall-mime.desktop", prefix, _("Software Manager"), _("Install new applications"), suffix)
