#!/bin/bash

intltool-extract --type=gettext/glade usr/share/linuxmint/mintinstall/mintinstall.glade

xgettext --language=Python --keyword=_ --output=mintinstall.pot \
  usr/lib/linuxmint/mintinstall/mintinstall.py \
  generate_desktop_files \
  usr/share/linuxmint/mintinstall/mintinstall.glade.h
xgettext --language=PolkitPolicy --its=polkit.its --output=mintinstall.pot --join-existing usr/share/polkit-1/actions/*.policy

rm -f usr/share/linuxmint/mintinstall/mintinstall.glade.h
